---
title: "EDA"
output: html_document
date: "2023-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r}
# install.packages("devtools")
devtools::install_github("wjonasreger/mousePreopticR")
```


```{r, message=FALSE}
library(here)
library(Matrix)
library(mousePreopticR)
library(monocle3)
library(tidyr)
library(tidyverse)

library(Seurat)
library(tidyverse)
library(dplyr)
library(patchwork)
library(monocle3)
library(SeuratWrappers)
```


## Load Data

```{r}
## compose datasets
#     - only need to run this once after installation. 
#     - may need to restart R session after composition.
composeData()

## load bio datasets
#     - mpr_matrix, mpr_genes, mpr_barcodes
#     - mpr_merfish
loadData()
```

```{r}
library(pheatmap)

cpm = apply(mpr_matrix[1:100, 1:100], 2, function(x) x/sum(x) * 10^6)
log_cpm = apply(cpm, 2, function(x) log(x+1))
cpm_sds = apply(log_cpm, 1, function(x) sd(x))
select_cpm = log_cpm[cpm_sds > 1, ]

pheatmap(select_cpm, scale = "row", show_rownames = FALSE, show_colnames = FALSE,
         clustering_distance_rows = 'correlation', clustering_distance_cols = 'correlation')
```



```{r}
## Create a Seurat object

# read in expression matrix data from local directory (or use mpr_matrix for example)
# mpr_data = readMPR(data.dir = "mpr_GSE113576")

mpr_seurat = CreateSeuratObject(counts = mpr_matrix)
# mpr_seurat = subset(mpr_seurat, subset = dpn > 0)
mpr_seurat
```


```{r}
## Remove low quality gene expressions by removing cells where mitochondrial genes comprise more tahn 10% of total RNA content

# is_mito = grep("^MT-", rowData(cds)$gene_short_name)
# 
# mpr_seurat = PercentageFeatureSet(mpr_seurat, pattern = "^mt:", col.name = "percent_mt")
# mpr_seurat = subset(mpr_seurat, subset = percent.mt <= 10)
# mpr_seurat
```

```{r}
VlnPlot(mpr_seurat, features = c("nFeature_RNA", "nCount_RNA", "percent_mt"), ncol = 3)
cutoff = 7000
mpr_seurat = subset(mpr_seurat, subset = nCount_RNA <= cutoff)
mpr_seurat
```

```{r}
# normalize
mpr_seurat = NormalizeData(mpr_seurat, verbose = FALSE)

# scale
all_genes = rownames(mpr_seurat)
mpr_seurat = ScaleData(mpr_seurat, features = all_genes, verbose = FALSE)

# most variable genes
mpr_seurat = FindVariableFeatures(mpr_seurat, verbose = FALSE)

# most variable genes
most_variable = head(VariableFeatures(mpr_seurat), 5)
most_variable
```

```{r}
# linear dimensional reduction with PCA
mpr_seurat = RunPCA(mpr_seurat, verbose = FALSE)

ElbowPlot(mpr_seurat)
```


```{r}
# find neighbors
mpr_seurat = FindNeighbors(mpr_seurat, dims = 1:10, verbose = FALSE)
# find clusters
mpr_seurat = FindClusters(mpr_seurat, resolution = 0.12, verbose = TRUE)

table(Idents(mpr_seurat))
```

```{r}
mpr_seurat = RunUMAP(mpr_seurat, dims = 1:10, verbose = FALSE)
DimPlot(mpr_seurat, reduction = "umap", label = TRUE)
```

```{r}
mpr_markers = FindAllMarkers(mpr_seurat, verbose = FALSE)
diff_exp = mpr_markers %>%
  group_by(cluster) %>%
  filter(avg_log2FC >= 1.5) %>%
  filter(p_val_adj <= 0.05) %>%
  arrange(desc(avg_log2FC))

head(diff_exp)
```

```{r}
table(diff_exp$cluster)
```

```{r}
FeaturePlot(mpr_seurat, features = diff_exp$gene[1], combine = TRUE)
```

```{r}

```



















```{r, warning=FALSE}
## create a monocle CellDataSet object
cds = new_cell_data_set(expression_data = mpr_matrix,
                        cell_metadata = mpr_barcodes,
                        gene_metadata = mpr_genes)

cds
```




```{r}
# sapply(mat@Dimnames, length)
# sapply(mat@Dimnames, function(i) length(unique(i)))
# 
# counts = mat
# row_data = data.frame(gene_short_name = mat@Dimnames[[1]])
# rownames(row_data) = row_data$gene_short_name
# col_data = data.frame(barcode = mat@Dimnames[[2]])
# rownames(col_data) = col_data$barcode
# 
# spatial_coords = as.matrix(tmp_DRYAD[, meta_columns[2:3]])
# colnames(spatial_coords) = c("x", "y")
# 
# spatial_coords
# 
# spe <- SpatialExperiment(
#   assays = list(counts = counts), 
#   rowData = row_data, 
#   colData = col_data,
#   spatialCoords = spatial_coords
# )
# 
# spe

```

```{r}
# nrows <- 200; ncols <- 6
# counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
# colData <- DataFrame(Treatment=rep(c("ChIP", "Input"), 3),
#                      row.names=LETTERS[1:6])
# colData
# counts
# 
# mat
# 
# se0 <- SummarizedExperiment(assays=SimpleList(counts=counts),
#                             colData=colData)
# 
# spe <- SpatialExperiment(
#   se0
# )
# 
# spe
```



```{r}
dryad = utils::read.table(file = "merfish.csv", header = TRUE, sep = ",")
summary(dryad[, c("Centroid_X", "Centroid_Y")])
```


```{r}
xlim = c(-2500, -2000)
xind = (dryad$Centroid_X < xlim[2]) & (dryad$Centroid_X > xlim[1])
ylim = c(-250, 250)
yind = (dryad$Centroid_Y < ylim[2]) & (dryad$Centroid_Y > ylim[1])
tmp_dryad = dryad[xind & yind, ]
summary(tmp_dryad[, c("Centroid_X", "Centroid_Y")])
dim(tmp_dryad)
```

```{r}
plot(tmp_dryad$Centroid_X, tmp_dryad$Centroid_Y)
```


```{r}
write.table(tmp_dryad, "mpr_merfish_sample.tsv", sep = "\t", row.names = FALSE, col.names = TRUE)
dryad_read = utils::read.table(file = "mpr_merfish_sample.tsv", header = TRUE, sep = "\t")
head(dryad_read)
```

```{r}
tableSplit("mpr_merfish_sample.tsv", 3, axis = 0, header = FALSE, sep = '\t', verbose = FALSE)
```










